name: Build uf2

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Minify
        uses: creepinson/pnpm-action@master
        with:
          arguments: '["install", "start"]'
      - id: build-uf2
        name: Build uf2
        uses: pavelaron/dir2uf2-action@v0.1.0
        with:
          environment-file: 'enviro.txt'
          file-name: 'cocopool'
          src-dir: '.'
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cocopool
          path: ${{ steps.build-uf2.outputs.uf2-file }}
