name: Build uf2

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pavelaron/uf2-build:1.0
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Copy source
        run: cp -a /app/. /uf2-build/micropython/ports/rp2/modules/
      - name: Make
        working-directory: /uf2-build/micropython/ports/rp2
        run: |
          make submodules
          make clean
          make
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Firmware
          path: /uf2-build/micropython/ports/rp2/build-PICO/firmware.uf2
