name: Build

on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build .uf2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - id: build
        uses: actions/dir2uf2-action@main
        with:
          environment-file: 'enviro.txt'
          file-name: 'cocopool'
          src-dir: '.'
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: cocopool
          path: ${{ steps.build.outputs.uf2-file }}
